# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sight CI

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-deps-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        env:
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.SIGHT_RELEASE }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --win --mac
